version: '2'
services:
  web:
    build:
      context: ./
      dockerfile: web.docker
    ports:
      - "8080:80"
    volumes:
      - .:/srv/www
    links:
      - app
  app:
    build:
      context: ./
      dockerfile: app.docker
    volumes:
      - ./:/srv/www
    links:
      - redis
      - mysql
    environment:
      CACHE_DRIVER: redis
      DB_DATABASE: jotistry
      DB_HOST: mysql
      DB_PASSWORD: jotistry
      DB_USERNAME: jotistry
      REDIS_HOST: redis
      SESSION_DRIVER: redis
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: jotistry
      MYSQL_PASSWORD: jotistry
      MYSQL_ROOT_PASSWORD:
      MYSQL_USER: jotistry
    ports:
        - "3306:3306"
  redis:
    image: redis
