version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2-node-browsers
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t benovermyer/jotistry:$TAG -t benovermyer/jotistry:latest .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push benovermyer/jotistry:$TAG
          docker push benovermyer/jotistry:latest
workflows:
  version: 2
  build-and-publish:
    jobs:
      - build:
          filters:
            branches:
              only: master
